name: Publish NPM
on:
  workflow_dispatch:

  release:
    types: [published]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          yarn install
      - name: Publish to NPM
        run: |
          bash ./bin/publish-npm
        env:
          NPM_TOKEN: ${{ secrets.TENSORBASE_NPM_TOKEN || secrets.NPM_TOKEN }}